name: Deploy Next.js Standalone to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js 20 for build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Next.js app (standalone)
      - name: Build Next.js app
        run: npm run build

      # 5️⃣ Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      #    Copy Static Files

      - name: Copy Static Files
        run: |
          cp -r .next/static .next/standalone/.next/

      # 6️⃣ Prepare deployment ZIP
      - name: Prepare deployment ZIP
        run: |
          zip -r nextjs-app.zip \
            .next/standalone \
            .next/static \
            public \
            package.json \
            package-lock.json \
            -x '*.git*'

      # 7️⃣ Deploy ZIP to Azure Web App
      - name: Deploy to Azure Web App
        run: |
          az webapp deploy \
            --resource-group rg-nextjs-nonprod \
            --name react-app-third \
            --src-path nextjs-app.zip \
            --type zip
